[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
tokio-tungstenite = "0.30"
tracing = "0.1"
tracing-subscriber = "0.3"
color-eyre = "0.6"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
postcard = "1.1"
tokio = { version = "1.53.1", features = ["macros", "rt"] }
