[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.dependencies]
color-eyre = "0.6"
diesel = { version = "2.3", features = [
  "sqlite",
  "returning_clauses_for_sqlite_3_35",
] }
futures = "0.3"
insta = "1.48"
lexopt = "0.3.2"
pin-project-lite = "0.2"
postcard = "1.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_repr = "0.1"
tokio = { version = "1.53.1", features = ["macros", "rt"] }
tokio-tungstenite = { version = "0.30", features = [
  "rustls-tls-native-roots",
  "url",
] }
tracing = "0.1"
tracing-loki = { version = "0.2", default-features = false, features = [
  "rustls",
  "compat-0-2-1",
] }
tracing-subscriber = "0.3"
url = "2.5"
uuid = { version = "1.26", features = ["v7"] }
warp = { version = "0.4", features = ["websocket", "server"] }

# local dep
roasted-db = { path = "crates/db" }
roasted-db-schema = { path = "crates/db-schema" }
roasted-types = { path = "crates/types" }
