[package]
name = "roasted-types"
version = "0.1.0"
edition = "2024"

[dependencies]
bon.workspace = true
serde = { workspace = true, features = ["derive", "alloc"] }
serde_repr.workspace = true
url = { workspace = true, default-features = false }
zeroize = { workspace = true, features = ["alloc"] }

# optional
diesel = { workspace = true, optional = true }
uuid = { workspace = true, optional = true }

# local
roasted-db-schema = { workspace = true, optional = true }

[dev-dependencies]
insta.workspace = true
serde_json.workspace = true

[features]
std = []
default = ["std", "serde/std", "zeroize/std", "bon/std", "url/std"]
all = ["db", "ws", "zippy", "daemon"]
db = ["dep:diesel", "dep:roasted-db-schema", "dep:uuid"]
ws = []
zippy = []
daemon = []
