[package]
name = "roasted-zippy"
version = "0.1.0"
edition = "2024"
description = "ESP32 Audio/Microphone to roast your espresso"

[dependencies]
embassy-executor = "0.10.0"
embassy-sync = "0.8"
embassy-time = "0.5.0"
embedded-io-async = "0.7"
esp-alloc = { version = "0.11", features = ["esp32s3"] }
esp-backtrace = { version = "0.20.0", features = [
  "esp32s3",
  "panic-handler",
  "println",
] }
esp-bootloader-esp-idf = { version = "0.6.0", features = ["esp32s3"] }
esp-hal = { version = "~1.2.2", features = ["esp32s3", "unstable"] }
esp-println = { version = "0.18.0", default-features = false, features = [
  "esp32s3",
  "uart",
  "critical-section",
] }
esp-rtos = { version = "0.4.0", features = ["esp32s3", "embassy"] }
heapless = "0.9"
postcard.workspace = true
roasted-types = { workspace = true, default-features = false, features = [
  "zippy",
] }
static_cell.workspace = true
thiserror = { version = "2", default-features = false }

[[bin]]
name = "roasted-zippy"
path = "src/main.rs"
test = false
bench = false

[features]
default = []
qemu = []

[build-dependencies]
cfg_aliases = "0.2"
